export const wordData = {
  "verbs": [
    {"writing":"かかる","reading":"かかる","category":"verb","type":"u","eng":"to take (amount of time/money)","levels":["L10"],"kanji":"かかる"},
    {"writing":"とまる","reading":"泊まる","category":"verb","type":"u","eng":"to stay (at a hotel, etc.)","levels":["L10"],"kanji":"<ruby>泊<rt>と</rt></ruby>まる"},
    {"writing":"なる","reading":"なる","category":"verb","type":"u","eng":"to become","levels":["L10"],"kanji":"なる"},
    {"writing":"きめる","reading":"決める","category":"verb","type":"ru","eng":"to decide ","levels":["L10"],"kanji":"<ruby>決<rt>き</rt></ruby>める"},
    {"writing":"ごろごろする","reading":"ごろごろする","category":"verb","type":"irv","eng":"to chill out at home; to stay home do nothing ","levels":["L10"],"kanji":"ごろごろする"},
    {"writing":"りょこうする","reading":"旅行する","category":"verb","type":"irv","eng":"to travel ","levels":["L10"],"kanji":"<ruby>旅<rt>りょ</rt></ruby><ruby>行<rt>こう</rt></ruby>する"},
    {"writing":"れんしゅうする","reading":"練習する","category":"verb","type":"irv","eng":"to practice ","levels":["L10"],"kanji":"<ruby>練<rt>れん</rt></ruby><ruby>習<rt>しゅう</rt></ruby>する"},
    {"writing":"とる","reading":"とる","category":"verb","type":"u","eng":"to take off","levels":["L10"],"kanji":"とる"},
    {"writing":"うる","reading":"売る","category":"verb","type":"u","eng":"to sell","levels":["L10","L15"],"kanji":"<ruby>売<rt>う</rt></ruby>る"},
    {"writing":"びっくりする","reading":"びっくりする","category":"verb","type":"irv","eng":"to be surprised ","levels":["L10","L21"],"kanji":"びっくりする"},
    {"writing":"うそをつく","reading":"うそをつく","category":"verb","type":"u","eng":"to tell a lie","levels":["L11"],"kanji":"うそをつく"},
    {"writing":"おなかがすく","reading":"おなかがすく","category":"verb","type":"u","eng":"to become hungry","levels":["L11"],"kanji":"おなかがすく"},
    {"writing":"かう","reading":"飼う","category":"verb","type":"u","eng":"to own (a pet)","levels":["L11"],"kanji":"<ruby>飼<rt>か</rt></ruby>う"},
    {"writing":"サボる","reading":"サボる","category":"verb","type":"u","eng":"to cut (classes)","levels":["L11"],"kanji":"サボる"},
    {"writing":"ならう","reading":"習う","category":"verb","type":"u","eng":"to learn","levels":["L11"],"kanji":"<ruby>習<rt>なら</rt></ruby>う"},
    {"writing":"のぼる","reading":"登る","category":"verb","type":"u","eng":"to climb","levels":["L11"],"kanji":"<ruby>登<rt>のぼ</rt></ruby>る"},
    {"writing":"はしる","reading":"走る","category":"verb","type":"u","eng":"to run","levels":["L11"],"kanji":"<ruby>走<rt>はし</rt></ruby>る"},
    {"writing":"つかれる","reading":"疲れる","category":"verb","type":"ru","eng":"to get tired ","levels":["L11"],"kanji":"<ruby>疲<rt>つか</rt></ruby>れる"},
    {"writing":"やめる","reading":"やめる","category":"verb","type":"ru","eng":"to quit ","levels":["L11"],"kanji":"やめる"},
    {"writing":"けんかする","reading":"けんかする","category":"verb","type":"irv","eng":"to have a fight; to quarrel ","levels":["L11"],"kanji":"けんかする"},
    {"writing":"しょうかいする","reading":"紹介する","category":"verb","type":"irv","eng":"to introduce ","levels":["L11"],"kanji":"<ruby>紹<rt>しょう</rt></ruby><ruby>介<rt>かい</rt></ruby>する"},
    {"writing":"ダイエットする","reading":"ダイエットする","category":"verb","type":"irv","eng":"to go on a diet ","levels":["L11"],"kanji":"ダイエットする"},
    {"writing":"ちこくする","reading":"遅刻する","category":"verb","type":"irv","eng":"to be late (for an appointment) ","levels":["L11"],"kanji":"<ruby>遅<rt>ち</rt></ruby><ruby>刻<rt>こく</rt></ruby>する"},
    {"writing":"りゅうがくする","reading":"留学する","category":"verb","type":"irv","eng":"to study abroad ","levels":["L11"],"kanji":"<ruby>留<rt>りゅう</rt></ruby><ruby>学<rt>がく</rt></ruby>する"},
    {"writing":"あるく","reading":"歩く","category":"verb","type":"u","eng":"to walk","levels":["L12"],"kanji":"<ruby>歩<rt>ある</rt></ruby>く"},
    {"writing":"かぜをひく","reading":"風邪をひく","category":"verb","type":"u","eng":"to catch a cold","levels":["L12"],"kanji":"<ruby>風<rt>かぜ</rt></ruby>邪をひく"},
    {"writing":"きょうみがある","reading":"興味がある","category":"verb","type":"u","eng":"to be interested (in)","levels":["L12"],"kanji":"<ruby>興<rt>きょう</rt></ruby><ruby>味<rt>み</rt></ruby>がある"},
    {"writing":"なくす","reading":"なくす","category":"verb","type":"u","eng":"to lose","levels":["L12"],"kanji":"なくす"},
    {"writing":"ねつがある","reading":"熱がある","category":"verb","type":"u","eng":"to have a fever","levels":["L12"],"kanji":"<ruby>熱<rt>ねつ</rt></ruby>がある"},
    {"writing":"のどがかわく","reading":"喉が渇く","category":"verb","type":"u","eng":"to become thirsty","levels":["L12"],"kanji":"<ruby>喉<rt>のど</rt></ruby>が<ruby>渇<rt>かわ</rt></ruby>く"},
    {"writing":"はらう","reading":"払う","category":"verb","type":"u","eng":"to pay","levels":["L12"],"kanji":"<ruby>払<rt>はら</rt></ruby>う"},
    {"writing":"せきがでる","reading":"せきが出る","category":"verb","type":"ru","eng":"to cough ","levels":["L12"],"kanji":"せきが<ruby>出<rt>で</rt></ruby>る"},
    {"writing":"わかれる","reading":"別れる","category":"verb","type":"ru","eng":"to break up; to separate ","levels":["L12"],"kanji":"<ruby>別<rt>わか</rt></ruby>れる"},
    {"writing":"きんちょうする","reading":"緊張する","category":"verb","type":"irv","eng":"to get nervous ","levels":["L12"],"kanji":"<ruby>緊<rt>きん</rt></ruby><ruby>張<rt>ちょう</rt></ruby>する"},
    {"writing":"しんぱいする","reading":"心配する","category":"verb","type":"irv","eng":"to worry ","levels":["L12"],"kanji":"<ruby>心<rt>しん</rt></ruby><ruby>配<rt>ぱい</rt></ruby>する"},
    {"writing":"おこる","reading":"怒る","category":"verb","type":"u","eng":"to get angry","levels":["L12"],"kanji":"<ruby>怒<rt>おこ</rt></ruby>る"},
    {"writing":"かなう","reading":"かなう","category":"verb","type":"u","eng":"to be realized","levels":["L12"],"kanji":"かなう"},
    {"writing":"つれてかえる","reading":"連れて帰る","category":"verb","type":"u","eng":"to bring (a person) back","levels":["L12"],"kanji":"<ruby>連<rt>つ</rt></ruby>れて<ruby>帰<rt>かえ</rt></ruby>る"},
    {"writing":"はたをおる","reading":"はたを織る","category":"verb","type":"u","eng":"to weave","levels":["L12"],"kanji":"はたを<ruby>織<rt>お</rt></ruby>る"},
    {"writing":"なく","reading":"泣く","category":"verb","type":"u","eng":"to cry","levels":["L12","L13"],"kanji":"<ruby>泣<rt>な</rt></ruby>く"},
    {"writing":"はく","reading":"吐く","category":"verb","type":"u","eng":"to throw up","levels":["L12"],"kanji":"<ruby>吐<rt>は</rt></ruby>く"},
    {"writing":"こっせつする","reading":"骨折する","category":"verb","type":"irv","eng":"to break (a bone)","levels":["L12"],"kanji":"<ruby>骨<rt>こっ</rt></ruby><ruby>折<rt>せつ</rt></ruby>する"},
    {"writing":"めまいがする","reading":"めまいがする","category":"verb","type":"irv","eng":"to feel dizzy","levels":["L12"],"kanji":"めまいがする"},
    {"writing":"やけどをする","reading":"やけどをする","category":"verb","type":"irv","eng":"to burn oneself","levels":["L12"],"kanji":"やけどをする"},
    {"writing":"あむ","reading":"編む","category":"verb","type":"u","eng":"to knit","levels":["L13"],"kanji":"<ruby>編<rt>あ</rt></ruby>む"},
    {"writing":"がんばる","reading":"頑張る","category":"verb","type":"u","eng":"to do one’s best; to try hard","levels":["L13"],"kanji":"<ruby>頑<rt>がん</rt></ruby><ruby>張<rt>ば</rt></ruby>る"},
    {"writing":"みがく","reading":"磨く","category":"verb","type":"u","eng":"to brush (teeth); to polish","levels":["L13"],"kanji":"<ruby>磨<rt>みが</rt></ruby>く"},
    {"writing":"やくそくをまもる","reading":"約束を守る","category":"verb","type":"u","eng":"to keep a promise","levels":["L13"],"kanji":"<ruby>約<rt>やく</rt></ruby><ruby>束<rt>そく</rt></ruby>を<ruby>守<rt>まも</rt></ruby>る"},
    {"writing":"かんどうする","reading":"感動する","category":"verb","type":"irv","eng":"to be moved/touched (by...) ","levels":["L13"],"kanji":"<ruby>感<rt>かん</rt></ruby><ruby>動<rt>どう</rt></ruby>する"},
    {"writing":"ニヤニヤする","reading":"ニヤニヤする","category":"verb","type":"irv","eng":"to grin ","levels":["L13"],"kanji":"ニヤニヤする"},
    {"writing":"つく","reading":"着く","category":"verb","type":"u","eng":"to arrive","levels":["L13","L15"],"kanji":"<ruby>着<rt>つ</rt></ruby>く"},
    {"writing":"おくれる","reading":"遅れる","category":"verb","type":"ru","eng":"to become late ","levels":["L13","L19"],"kanji":"<ruby>遅<rt>おく</rt></ruby>れる"},
    {"writing":"おくる","reading":"送る","category":"verb","type":"u","eng":"to send","levels":["L14"],"kanji":"<ruby>送<rt>おく</rt></ruby>る"},
    {"writing":"にあう","reading":"似合う","category":"verb","type":"u","eng":"to look good (on somebody)","levels":["L14"],"kanji":"<ruby>似<rt>に</rt></ruby><ruby>合<rt>あ</rt></ruby>う"},
    {"writing":"あきらめる","reading":"あきらめる","category":"verb","type":"ru","eng":"to give up ","levels":["L14"],"kanji":"あきらめる"},
    {"writing":"あげる","reading":"あげる","category":"verb","type":"ru","eng":"to give (to others) ","levels":["L14"],"kanji":"あげる"},
    {"writing":"くれる","reading":"くれる","category":"verb","type":"ru","eng":"to give (me) ","levels":["L14"],"kanji":"くれる"},
    {"writing":"できる","reading":"できる","category":"verb","type":"ru","eng":"to come into existence; to be made ","levels":["L14"],"kanji":"できる"},
    {"writing":"そうだんする","reading":"相談する","category":"verb","type":"irv","eng":"to consult ","levels":["L14"],"kanji":"<ruby>相<rt>そう</rt></ruby><ruby>談<rt>だん</rt></ruby>する"},
    {"writing":"ちゅういする","reading":"注意する","category":"verb","type":"irv","eng":"to give warning; to watch out ","levels":["L14"],"kanji":"<ruby>注<rt>ちゅう</rt></ruby><ruby>意<rt>い</rt></ruby>する"},
    {"writing":"プロポーズする","reading":"プロポーズする","category":"verb","type":"irv","eng":"to propose marriage ","levels":["L14"],"kanji":"プロポーズする"},
    {"writing":"あいす","reading":"愛す","category":"verb","type":"u","eng":"to love","levels":["L14"],"kanji":"<ruby>愛<rt>あい</rt></ruby>す"},
    {"writing":"つきあう","reading":"付き合う","category":"verb","type":"u","eng":"to date (someone); to keep company","levels":["L14","L15"],"kanji":"<ruby>付<rt>つ</rt></ruby>き<ruby>合<rt>あ</rt></ruby>う"},
    {"writing":"おろす","reading":"下ろす","category":"verb","type":"u","eng":"to withdwriting (money)","levels":["L15"],"kanji":"<ruby>下<rt>お</rt></ruby>ろす"},
    {"writing":"かく","reading":"描く","category":"verb","type":"u","eng":"to dwriting; to paint","levels":["L15"],"kanji":"<ruby>描<rt>か</rt></ruby>く"},
    {"writing":"さがす","reading":"探す","category":"verb","type":"u","eng":"to look for","levels":["L15"],"kanji":"<ruby>探<rt>さが</rt></ruby>す"},
    {"writing":"さそう","reading":"誘う","category":"verb","type":"u","eng":"to invite","levels":["L15"],"kanji":"<ruby>誘<rt>さそ</rt></ruby>う"},
    {"writing":"しゃべる","reading":"しゃべる","category":"verb","type":"u","eng":"to chat","levels":["L15"],"kanji":"しゃべる"},
    {"writing":"ほけんにはいる","reading":"保険に入る","category":"verb","type":"u","eng":"to buy insurance","levels":["L15"],"kanji":"<ruby>保<rt>ほ</rt></ruby><ruby>険<rt>けん</rt></ruby>に<ruby>入<rt>はい</rt></ruby>る"},
    {"writing":"きをつける","reading":"気をつける","category":"verb","type":"ru","eng":"to be cautious/careful ","levels":["L15"],"kanji":"<ruby>気<rt>き</rt></ruby>をつける"},
    {"writing":"しらべる","reading":"調べる","category":"verb","type":"ru","eng":"to look into (a matter) ","levels":["L15"],"kanji":"<ruby>調<rt>しら</rt></ruby>べる"},
    {"writing":"みえる","reading":"見える","category":"verb","type":"ru","eng":"to be visible ","levels":["L15"],"kanji":"<ruby>見<rt>み</rt></ruby>える"},
    {"writing":"かんこうする","reading":"観光する","category":"verb","type":"irv","eng":"to do sightseeing ","levels":["L15"],"kanji":"<ruby>観<rt>かん</rt></ruby><ruby>光<rt>こう</rt></ruby>する"},
    {"writing":"さんかする","reading":"参加する","category":"verb","type":"irv","eng":"to participate ","levels":["L15"],"kanji":"<ruby>参<rt>さん</rt></ruby><ruby>加<rt>か</rt></ruby>する"},
    {"writing":"する","reading":"する","category":"verb","type":"irv","eng":"to decide on (an item) ","levels":["L15"],"kanji":"する"},
    {"writing":"そつぎょうする","reading":"卒業する","category":"verb","type":"irv","eng":"to graduate (from...) ","levels":["L15"],"kanji":"<ruby>卒<rt>そつ</rt></ruby><ruby>業<rt>ぎょう</rt></ruby>する"},
    {"writing":"はっぴょうする","reading":"発表する","category":"verb","type":"irv","eng":"to make a presentation; to make public ","levels":["L15"],"kanji":"<ruby>発<rt>は</rt></ruby><ruby>表<rt>っぴょう</rt></ruby>する"},
    {"writing":"よやくする","reading":"予約する","category":"verb","type":"irv","eng":"to reserve ","levels":["L15"],"kanji":"<ruby>予<rt>よ</rt></ruby><ruby>約<rt>やく</rt></ruby>する"},
    {"writing":"たのしむ","reading":"楽しむ","category":"verb","type":"u","eng":"to enjoy","levels":["L15"],"kanji":"<ruby>楽<rt>たの</rt></ruby>しむ"},
    {"writing":"とおる","reading":"通る","category":"verb","type":"u","eng":"to go through; to pass","levels":["L15"],"kanji":"<ruby>通<rt>とお</rt></ruby>る"},
    {"writing":"のこす","reading":"残す","category":"verb","type":"u","eng":"to leave; to preserve","levels":["L15"],"kanji":"<ruby>残<rt>のこ</rt></ruby>す"},
    {"writing":"まちあわせをする","reading":"待ち合わせをする","category":"verb","type":"irv","eng":"to meet up ","levels":["L15"],"kanji":"<ruby>待<rt>ま</rt></ruby>ち<ruby>合<rt>あ</rt></ruby>わせをする"},
    {"writing":"こむ","reading":"混む","category":"verb","type":"u","eng":"to get crowded","levels":["L15","L17"],"kanji":"<ruby>混<rt>こ</rt></ruby>む"},
    {"writing":"うまれる","reading":"生まれる","category":"verb","type":"ru","eng":"to be born ","levels":["L15","L17"],"kanji":"<ruby>生<rt>う</rt></ruby>まれる"},
    {"writing":"チェックアウト","suffix":"（する）","reading":"チェックアウト","category":"verb","type":"irv","eng":"checking out","levels":["L15"],"kanji":"チェックアウト"},
    {"writing":"チェックイン","suffix":"（する）","reading":"チェックイン","category":"verb","type":"irv","eng":"checking in","levels":["L15"],"kanji":"チェックイン"},
    {"writing":"おこす","reading":"起こす","category":"verb","type":"u","eng":"to wake (someone) up","levels":["L16"],"kanji":"<ruby>起<rt>お</rt></ruby>こす"},
    {"writing":"おごる","reading":"おごる","category":"verb","type":"u","eng":"to treat (someone) to a meal","levels":["L16"],"kanji":"おごる"},
    {"writing":"おちこむ","reading":"落ち込む","category":"verb","type":"u","eng":"to get depressed","levels":["L16"],"kanji":"<ruby>落<rt>お</rt></ruby>ち<ruby>込<rt>こ</rt></ruby>む"},
    {"writing":"かす","reading":"貸す","category":"verb","type":"u","eng":"to lend","levels":["L16"],"kanji":"<ruby>貸<rt>か</rt></ruby>す"},
    {"writing":"こまる","reading":"困る","category":"verb","type":"u","eng":"to have difficulty","levels":["L16"],"kanji":"<ruby>困<rt>こま</rt></ruby>る"},
    {"writing":"だす","reading":"出す","category":"verb","type":"u","eng":"to take (something) out; to hand in (something)","levels":["L16"],"kanji":"<ruby>出<rt>だ</rt></ruby>す"},
    {"writing":"つれていく","reading":"連れていく","category":"verb","type":"u","eng":"to take (someone) to (a place)","levels":["L16"],"kanji":"<ruby>連<rt>つ</rt></ruby>れていく"},
    {"writing":"なおす","reading":"直す","category":"verb","type":"u","eng":"to correct; to fix","levels":["L16"],"kanji":"<ruby>直<rt>なお</rt></ruby>す"},
    {"writing":"みちにまよう","reading":"道に迷う","category":"verb","type":"u","eng":"to become lost; to lose one’s way","levels":["L16"],"kanji":"<ruby>道<rt>みち</rt></ruby>に<ruby>迷<rt>まよ</rt></ruby>う"},
    {"writing":"みつかる","reading":"見つかる","category":"verb","type":"u","eng":"to be found","levels":["L16"],"kanji":"<ruby>見<rt>み</rt></ruby>つかる"},
    {"writing":"むかえにいく","reading":"迎えに行く","category":"verb","type":"u","eng":"to go to pick up","levels":["L16"],"kanji":"<ruby>迎<rt>むか</rt></ruby>えに<ruby>行<rt>い</rt></ruby>く"},
    {"writing":"やくす","reading":"訳す","category":"verb","type":"u","eng":"to translate","levels":["L16"],"kanji":"<ruby>訳<rt>やく</rt></ruby>す"},
    {"writing":"わらう","reading":"笑う","category":"verb","type":"u","eng":"to laugh","levels":["L16"],"kanji":"<ruby>笑<rt>わら</rt></ruby>う"},
    {"writing":"アイロンをかける","reading":"アイロンをかける","category":"verb","type":"ru","eng":"to iron (clothes) ","levels":["L16"],"kanji":"アイロンをかける"},
    {"writing":"あつめる","reading":"集める","category":"verb","type":"ru","eng":"to collect ","levels":["L16"],"kanji":"<ruby>集<rt>あつ</rt></ruby>める"},
    {"writing":"いれる","reading":"入れる","category":"verb","type":"ru","eng":"to put (something) in ","levels":["L16"],"kanji":"<ruby>入<rt>い</rt></ruby>れる"},
    {"writing":"かける","suffix":"（アイロンを）","reading":"かける","category":"verb","type":"ru","eng":"to iron (clothes) ","levels":["L16"],"kanji":"かける"},
    {"writing":"のりおくれる","reading":"乗り遅れる","category":"verb","type":"ru","eng":"to miss (a train, bus, etc.) ","levels":["L16"],"kanji":"<ruby>乗<rt>の</rt></ruby>り<ruby>遅<rt>おく</rt></ruby>れる"},
    {"writing":"みせる","reading":"見せる","category":"verb","type":"ru","eng":"to show ","levels":["L16"],"kanji":"<ruby>見<rt>み</rt></ruby>せる"},
    {"writing":"あさねぼうする","reading":"朝寝坊する","category":"verb","type":"irv","eng":"to oversleep ","levels":["L16"],"kanji":"<ruby>朝<rt>あさ</rt></ruby><ruby>寝<rt>ね</rt></ruby><ruby>坊<rt>ぼう</rt></ruby>する"},
    {"writing":"せつめいする","reading":"説明する","category":"verb","type":"irv","eng":"to explain ","levels":["L16"],"kanji":"<ruby>説<rt>せつ</rt></ruby><ruby>明<rt>めい</rt></ruby>する"},
    {"writing":"むかえにくる","reading":"迎えに来る","category":"verb","type":"irv","eng":"to come to pick up ","levels":["L16"],"kanji":"<ruby>迎<rt>むか</rt></ruby>えに<ruby>来<rt>く</rt></ruby>る"},
    {"writing":"うつす","reading":"写す","category":"verb","type":"u","eng":"to copy","levels":["L16"],"kanji":"<ruby>写<rt>うつ</rt></ruby>す"},
    {"writing":"つづく","reading":"続く","category":"verb","type":"u","eng":"to continue","levels":["L16"],"kanji":"<ruby>続<rt>つづ</rt></ruby>く"},
    {"writing":"とぶ","reading":"飛ぶ","category":"verb","type":"u","eng":"to fly","levels":["L16"],"kanji":"<ruby>飛<rt>と</rt></ruby>ぶ"},
    {"writing":"もどる","reading":"戻る","category":"verb","type":"u","eng":"to return; to come/go back","levels":["L16","L20"],"kanji":"<ruby>戻<rt>もど</rt></ruby>る"},
    {"writing":"たすける","reading":"助ける","category":"verb","type":"ru","eng":"to help; to rescue ","levels":["L16","L22"],"kanji":"<ruby>助<rt>たす</rt></ruby>ける"},
    {"writing":"ちがう","reading":"違う","category":"verb","type":"u","eng":"to be different; to be wrong","levels":["L16","L23"],"kanji":"<ruby>違<rt>ちが</rt></ruby>う"},
    {"writing":"えらぶ","reading":"選ぶ","category":"verb","type":"u","eng":"to choose; to select","levels":["L17"],"kanji":"<ruby>選<rt>えら</rt></ruby>ぶ"},
    {"writing":"おゆをわかす","reading":"お湯を沸かす","category":"verb","type":"u","eng":"to boil water","levels":["L17"],"kanji":"お<ruby>湯<rt>ゆ</rt></ruby>を<ruby>沸<rt>わ</rt></ruby>かす"},
    {"writing":"かみをとかす","reading":"髪をとかす","category":"verb","type":"u","eng":"to comb one’s hair","levels":["L17"],"kanji":"<ruby>髪<rt>かみ</rt></ruby>をとかす"},
    {"writing":"たからくじにあたる","reading":"宝くじに当たる","category":"verb","type":"u","eng":"to win a lottery","levels":["L17"],"kanji":"<ruby>宝<rt>たから</rt></ruby>くじに<ruby>当<rt>あ</rt></ruby>たる"},
    {"writing":"ぬぐ","reading":"脱ぐ","category":"verb","type":"u","eng":"to take off (clothes)","levels":["L17"],"kanji":"<ruby>脱<rt>ぬ</rt></ruby>ぐ"},
    {"writing":"ひげをそる","reading":"ひげをそる","category":"verb","type":"u","eng":"to shave one’s beard","levels":["L17"],"kanji":"ひげをそる"},
    {"writing":"いれる","reading":"いれる","category":"verb","type":"ru","eng":"to make tea, coffee, etc. ","levels":["L17"],"kanji":"いれる"},
    {"writing":"かぎをかける","reading":"鍵をかける","category":"verb","type":"ru","eng":"to lock ","levels":["L17"],"kanji":"<ruby>鍵<rt>かぎ</rt></ruby>をかける"},
    {"writing":"かける","suffix":"（かぎを）","reading":"かける","suffix-reading":"（鍵を）","category":"verb","type":"ru","eng":"to lock ","levels":["L17"],"kanji":"かける"},
    {"writing":"たりる","reading":"足りる","category":"verb","type":"ru","eng":"to be sufficient; to be enough ","levels":["L17"],"kanji":"<ruby>足<rt>た</rt></ruby>りる"},
    {"writing":"なれる","reading":"慣れる","category":"verb","type":"ru","eng":"to get used to...","levels":["L17"],"kanji":"<ruby>慣<rt>な</rt></ruby>れる"},
    {"writing":"おいのりする","reading":"お祈りする","category":"verb","type":"irv","eng":"to pray ","levels":["L17"],"kanji":"お<ruby>祈<rt>いの</rt></ruby>りする"},
    {"writing":"けしょうする","reading":"化粧する","category":"verb","type":"irv","eng":"to put makeup on ","levels":["L17"],"kanji":"<ruby>化<rt>け</rt></ruby><ruby>粧<rt>しょう</rt></ruby>する"},
    {"writing":"しゅうしょくする","reading":"就職する","category":"verb","type":"irv","eng":"to get a full-time job (at...) ","levels":["L17"],"kanji":"<ruby>就<rt>しゅう</rt></ruby><ruby>職<rt>しょく</rt></ruby>する"},
    {"writing":"する","reading":"する","category":"verb","type":"irv","eng":"to wear small items (necktie, watch, etc.) ","levels":["L17"],"kanji":"する"},
    {"writing":"りこんする","reading":"離婚する","category":"verb","type":"irv","eng":"to get a divorce ","levels":["L17"],"kanji":"<ruby>離<rt>り</rt></ruby><ruby>婚<rt>こん</rt></ruby>する"},
    {"writing":"えいきょうをうける","reading":"影響を受ける","category":"verb","type":"ru","eng":"to be affected ","levels":["L17"],"kanji":"<ruby>影<rt>えい</rt></ruby><ruby>響<rt>きょう</rt></ruby>を<ruby>受<rt>う</rt></ruby>ける"},
    {"writing":"かぞえる","reading":"数える","category":"verb","type":"ru","eng":"to count ","levels":["L17"],"kanji":"<ruby>数<rt>かぞ</rt></ruby>える"},
    {"writing":"なまえをつける","reading":"名前をつける","category":"verb","type":"ru","eng":"to name ","levels":["L17"],"kanji":"<ruby>名<rt>な</rt></ruby><ruby>前<rt>まえ</rt></ruby>をつける"},
    {"writing":"かんせいする","reading":"完成する","category":"verb","type":"irv","eng":"to be completed ","levels":["L17"],"kanji":"<ruby>完<rt>かん</rt></ruby><ruby>成<rt>せい</rt></ruby>する"},
    {"writing":"かる","reading":"刈る","category":"verb","type":"u","eng":"to crop","levels":["L17"],"kanji":"<ruby>刈<rt>か</rt></ruby>る"},
    {"writing":"すく","reading":"すく","category":"verb","type":"u","eng":"thin out (hair)","levels":["L17"],"kanji":"すく"},
    {"writing":"そる","reading":"そる","category":"verb","type":"u","eng":"to shave","levels":["L17"],"kanji":"そる"},
    {"writing":"かける","suffix":"（パーマを）","reading":"かける","category":"verb","type":"ru","eng":"to have one’s hair permed ","levels":["L17"],"kanji":"かける"},
    {"writing":"そめる","reading":"そめる","category":"verb","type":"ru","eng":"to dye ","levels":["L17"],"kanji":"そめる"},
    {"writing":"そろえる","reading":"そろえる","category":"verb","type":"ru","eng":"to make hair even; to trim ","levels":["L17"],"kanji":"そろえる"},
    {"writing":"パーマをかける","reading":"パーマをかける","category":"verb","type":"ru","eng":"to have one’s hair permed ","levels":["L17"],"kanji":"パーマをかける"},
    {"writing":"あく","reading":"開く","category":"verb","type":"u","eng":"(something) opens","levels":["L18"],"kanji":"<ruby>開<rt>あ</rt></ruby>く"},
    {"writing":"あやまる","reading":"謝る","category":"verb","type":"u","eng":"to apologize","levels":["L18"],"kanji":"<ruby>謝<rt>あやま</rt></ruby>る"},
    {"writing":"おす","reading":"押す","category":"verb","type":"u","eng":"to press; to push","levels":["L18"],"kanji":"<ruby>押<rt>お</rt></ruby>す"},
    {"writing":"おとす","reading":"落とす","category":"verb","type":"u","eng":"to drop (something)","levels":["L18"],"kanji":"<ruby>落<rt>お</rt></ruby>とす"},
    {"writing":"おゆがわく","reading":"お湯が沸く","category":"verb","type":"u","eng":"water boils","levels":["L18"],"kanji":"お<ruby>湯<rt>ゆ</rt></ruby>が<ruby>沸<rt>わ</rt></ruby>く"},
    {"writing":"ころぶ","reading":"転ぶ","category":"verb","type":"u","eng":"to fall down","levels":["L18"],"kanji":"<ruby>転<rt>ころ</rt></ruby>ぶ"},
    {"writing":"こわす","reading":"壊す","category":"verb","type":"u","eng":"to break (something)","levels":["L18"],"kanji":"<ruby>壊<rt>こわ</rt></ruby>す"},
    {"writing":"さく","reading":"咲く","category":"verb","type":"u","eng":"to bloom","levels":["L18"],"kanji":"<ruby>咲<rt>さ</rt></ruby>く"},
    {"writing":"しまる","reading":"閉まる","category":"verb","type":"u","eng":"(something) closes","levels":["L18"],"kanji":"<ruby>閉<rt>し</rt></ruby>まる"},
    {"writing":"たすかる","reading":"助かる","category":"verb","type":"u","eng":"to be saved; to be helped","levels":["L18"],"kanji":"<ruby>助<rt>たす</rt></ruby>かる"},
    {"writing":"たのむ","reading":"頼む","category":"verb","type":"u","eng":"to ask (a favor)","levels":["L18"],"kanji":"<ruby>頼<rt>たの</rt></ruby>む"},
    {"writing":"つく","reading":"つく","category":"verb","type":"u","eng":"(something) turns on","levels":["L18"],"kanji":"つく"},
    {"writing":"よごす","reading":"汚す","category":"verb","type":"u","eng":"to make dirty","levels":["L18"],"kanji":"<ruby>汚<rt>よご</rt></ruby>す"},
    {"writing":"おちる","reading":"落ちる","category":"verb","type":"ru","eng":"(something) drops ","levels":["L18"],"kanji":"<ruby>落<rt>お</rt></ruby>ちる"},
    {"writing":"かたづける","reading":"片付ける","category":"verb","type":"ru","eng":"to tidy up ","levels":["L18"],"kanji":"<ruby>片<rt>かた</rt></ruby><ruby>付<rt>づ</rt></ruby>ける"},
    {"writing":"かんがえる","reading":"考える","category":"verb","type":"ru","eng":"to think (about); to consider ","levels":["L18"],"kanji":"<ruby>考<rt>かんが</rt></ruby>える"},
    {"writing":"きえる","reading":"消える","category":"verb","type":"ru","eng":"(something) goes off ","levels":["L18"],"kanji":"<ruby>消<rt>き</rt></ruby>える"},
    {"writing":"こわれる","reading":"壊れる","category":"verb","type":"ru","eng":"(something) breaks ","levels":["L18"],"kanji":"<ruby>壊<rt>こわ</rt></ruby>れる"},
    {"writing":"よごれる","reading":"汚れる","category":"verb","type":"ru","eng":"to become dirty ","levels":["L18"],"kanji":"<ruby>汚<rt>よご</rt></ruby>れる"},
    {"writing":"ちゅうもんする","reading":"注文する","category":"verb","type":"irv","eng":"to place an order ","levels":["L18"],"kanji":"<ruby>注<rt>ちゅう</rt></ruby><ruby>文<rt>もん</rt></ruby>する"},
    {"writing":"ちょきんする","reading":"貯金する","category":"verb","type":"irv","eng":"to deposit money (in a bank) ","levels":["L18"],"kanji":"<ruby>貯<rt>ちょ</rt></ruby><ruby>金<rt>きん</rt></ruby>する"},
    {"writing":"いらっしゃる","reading":"いらっしゃる","category":"verb","type":"u","eng":"honorific expression for いく, くる, and いる","levels":["L19"],"kanji":"いらっしゃる"},
    {"writing":"おくる","reading":"送る","category":"verb","type":"u","eng":"to walk/drive (someone)","levels":["L19"],"kanji":"<ruby>送<rt>おく</rt></ruby>る"},
    {"writing":"おっしゃる","reading":"おっしゃる","category":"verb","type":"u","eng":"honorific expression for いう","levels":["L19"],"kanji":"おっしゃる"},
    {"writing":"おやすみになる","reading":"お休みになる","category":"verb","type":"u","eng":"honorific expression for ねる","levels":["L19"],"kanji":"お<ruby>休<rt>やす</rt></ruby>みになる"},
    {"writing":"きまる","reading":"決まる","category":"verb","type":"u","eng":"to be decided","levels":["L19"],"kanji":"<ruby>決<rt>き</rt></ruby>まる"},
    {"writing":"くださる","reading":"下さる","category":"verb","type":"u","eng":"honorific expression for くれる","levels":["L19"],"kanji":"<ruby>下<rt>くだ</rt></ruby>さる"},
    {"writing":"ごらんになる","reading":"ご覧になる","category":"verb","type":"u","eng":"honorific expression for みる","levels":["L19"],"kanji":"ご<ruby>覧<rt>らん</rt></ruby>になる"},
    {"writing":"しりあう","reading":"知り合う","category":"verb","type":"u","eng":"to get acquainted with","levels":["L19"],"kanji":"<ruby>知<rt>し</rt></ruby>り<ruby>合<rt>あ</rt></ruby>う"},
    {"writing":"ていらっしゃる","prefix":"～","reading":"ていらっしゃる","category":"verb","type":"u","eng":"honorific expression for ～ている","levels":["L19"],"kanji":"ていらっしゃる"},
    {"writing":"なさる","reading":"なさる","category":"verb","type":"u","eng":"honorific expression for する","levels":["L19"],"kanji":"なさる"},
    {"writing":"ひっこす","reading":"引っ越す","category":"verb","type":"u","eng":"to move (to another place to live)","levels":["L19"],"kanji":"<ruby>引<rt>ひ</rt></ruby>っ<ruby>越<rt>こ</rt></ruby>す"},
    {"writing":"めしあがる","reading":"召し上がる","category":"verb","type":"u","eng":"honorific expression for たべる and のむ","levels":["L19"],"kanji":"<ruby>召<rt>め</rt></ruby>し<ruby>上<rt>あ</rt></ruby>がる"},
    {"writing":"よぶ","reading":"呼ぶ","category":"verb","type":"u","eng":"to call (one’s name); to invite","levels":["L19"],"kanji":"<ruby>呼<rt>よ</rt></ruby>ぶ"},
    {"writing":"よる","reading":"寄る","category":"verb","type":"u","eng":"to stop by","levels":["L19"],"kanji":"<ruby>寄<rt>よ</rt></ruby>る"},
    {"writing":"かける","reading":"かける","category":"verb","type":"ru","eng":"to sit down ","levels":["L19"],"kanji":"かける"},
    {"writing":"はれる","reading":"晴れる","category":"verb","type":"ru","eng":"to become sunny ","levels":["L19"],"kanji":"<ruby>晴<rt>は</rt></ruby>れる"},
    {"writing":"もてる","reading":"もてる","category":"verb","type":"ru","eng":"to be popular (in terms of romantic interest) ","levels":["L19"],"kanji":"もてる"},
    {"writing":"えんりょする","reading":"遠慮する","category":"verb","type":"irv","eng":"to hold back for the time being; to refrain from ","levels":["L19"],"kanji":"<ruby>遠<rt>えん</rt></ruby><ruby>慮<rt>りょ</rt></ruby>する"},
    {"writing":"ごちそうする","reading":"ごちそうする","category":"verb","type":"irv","eng":"to treat/invite (someone) to a meal ","levels":["L19"],"kanji":"ごちそうする"},
    {"writing":"しょうたいする","reading":"招待する","category":"verb","type":"irv","eng":"to invite someone (to an event/a place) ","levels":["L19"],"kanji":"<ruby>招<rt>しょう</rt></ruby><ruby>待<rt>たい</rt></ruby>する"},
    {"writing":"おもいだす","reading":"思い出す","category":"verb","type":"u","eng":"to recall","levels":["L19"],"kanji":"<ruby>思<rt>おも</rt></ruby>い<ruby>出<rt>だ</rt></ruby>す"},
    {"writing":"たつ","reading":"たつ","category":"verb","type":"u","eng":"(time) pass","levels":["L19"],"kanji":"たつ"},
    {"writing":"たいせつにする","reading":"大切にする","category":"verb","type":"irv","eng":"to take good care of ","levels":["L19"],"kanji":"<ruby>大<rt>たい</rt></ruby><ruby>切<rt>せつ</rt></ruby>にする"},
    {"writing":"おせわになる","reading":"お世話になる","category":"verb","type":"u","eng":"to be in someone’s care","levels":["L19","L23"],"kanji":"お<ruby>世<rt>せ</rt></ruby><ruby>話<rt>わ</rt></ruby>になる"},
    {"writing":"うける","reading":"受ける","category":"verb","type":"ru","eng":"to take (an examination) ","levels":["L19","L22"],"kanji":"<ruby>受<rt>う</rt></ruby>ける"},
    {"writing":"いたす","reading":"致す","category":"verb","type":"u","eng":"extra-modest expression for する","levels":["L20"],"kanji":"<ruby>致<rt>いた</rt></ruby>す"},
    {"writing":"いただく","reading":"頂く","category":"verb","type":"u","eng":"extra-modest expression for たべる and のむ","levels":["L20"],"kanji":"<ruby>頂<rt>いただ</rt></ruby>く"},
    {"writing":"いただく","reading":"頂く","category":"verb","type":"u","eng":"humble expression for もらう","levels":["L20"],"kanji":"<ruby>頂<rt>いただ</rt></ruby>く"},
    {"writing":"うかがう","reading":"伺う","category":"verb","type":"u","eng":"to humbly visit; to humbly ask","levels":["L20"],"kanji":"<ruby>伺<rt>うかが</rt></ruby>う"},
    {"writing":"おる","reading":"おる","category":"verb","type":"u","eng":"extra-modest expression for いる","levels":["L20"],"kanji":"おる"},
    {"writing":"ござる","reading":"ござる","category":"verb","type":"u","eng":"extra-modest expression for ある","levels":["L20"],"kanji":"ござる"},
    {"writing":"ておる","prefix":"～","reading":"ておる","category":"verb","type":"u","eng":"extra-modest expression for ～ている","levels":["L20"],"kanji":"ておる"},
    {"writing":"でござる","prefix":"～","reading":"でござる","category":"verb","type":"u","eng":"extra-modest expression for です","levels":["L20"],"kanji":"でござる"},
    {"writing":"まいる","reading":"参る","category":"verb","type":"u","eng":"extra-modest expression for いく and くる","levels":["L20"],"kanji":"<ruby>参<rt>まい</rt></ruby>る"},
    {"writing":"もうす","reading":"申す","category":"verb","type":"u","eng":"extra-modest expression for いう","levels":["L20"],"kanji":"<ruby>申<rt>もう</rt></ruby>す"},
    {"writing":"きこえる","reading":"聞こえる","category":"verb","type":"ru","eng":"to be audible ","levels":["L20"],"kanji":"<ruby>聞<rt>き</rt></ruby>こえる"},
    {"writing":"さしあげる","reading":"差し上げる","category":"verb","type":"ru","eng":"humble expression for あげる ","levels":["L20"],"kanji":"<ruby>差<rt>さ</rt></ruby>し<ruby>上<rt>あ</rt></ruby>げる"},
    {"writing":"つたえる","reading":"伝える","category":"verb","type":"ru","eng":"to convey message ","levels":["L20"],"kanji":"<ruby>伝<rt>つた</rt></ruby>える"},
    {"writing":"つづける","reading":"続ける","category":"verb","type":"ru","eng":"to continue ","levels":["L20"],"kanji":"<ruby>続<rt>つづ</rt></ruby>ける"},
    {"writing":"またせる","reading":"待たせる","category":"verb","type":"ru","eng":"to keep (someone) waiting ","levels":["L20"],"kanji":"<ruby>待<rt>ま</rt></ruby>たせる"},
    {"writing":"こうかんする","reading":"交換する","category":"verb","type":"irv","eng":"to exchange ","levels":["L20"],"kanji":"<ruby>交<rt>こう</rt></ruby><ruby>換<rt>かん</rt></ruby>する"},
    {"writing":"せいかつする","reading":"生活する","category":"verb","type":"irv","eng":"to lead a life ","levels":["L20"],"kanji":"<ruby>生<rt>せい</rt></ruby><ruby>活<rt>かつ</rt></ruby>する"},
    {"writing":"へんぴんする","reading":"返品する","category":"verb","type":"irv","eng":"to return (merchandise) ","levels":["L20"],"kanji":"<ruby>返<rt>へん</rt></ruby><ruby>品<rt>ぴん</rt></ruby>する"},
    {"writing":"だく","reading":"抱く","category":"verb","type":"u","eng":"to hold something in one’s arm","levels":["L20"],"kanji":"<ruby>抱<rt>だ</rt></ruby>く"},
    {"writing":"だます","reading":"だます","category":"verb","type":"u","eng":"to deceive","levels":["L20"],"kanji":"だます"},
    {"writing":"とまる","reading":"止まる","category":"verb","type":"u","eng":"to stop","levels":["L20"],"kanji":"<ruby>止<rt>と</rt></ruby>まる"},
    {"writing":"ひっかく","reading":"ひっかく","category":"verb","type":"u","eng":"to scratch","levels":["L20"],"kanji":"ひっかく"},
    {"writing":"わたす","reading":"渡す","category":"verb","type":"u","eng":"to give; to hand","levels":["L20"],"kanji":"<ruby>渡<rt>わた</rt></ruby>す"},
    {"writing":"うれる","reading":"売れる","category":"verb","type":"ru","eng":"to be sold ","levels":["L20"],"kanji":"<ruby>売<rt>う</rt></ruby>れる"},
    {"writing":"する","reading":"する","category":"verb","type":"irv","eng":"to cost ","levels":["L20"],"kanji":"する"},
    {"writing":"にこにこする","reading":"にこにこする","category":"verb","type":"irv","eng":"to smile ","levels":["L20"],"kanji":"にこにこする"},
    {"writing":"がっかりする","reading":"がっかりする","category":"verb","type":"irv","eng":"to be disappointed ","levels":["L20","L23"],"kanji":"がっかりする"},
    {"writing":"いう（もんくを）","suffix":"（もんくを）","reading":"言う（文句を）","category":"verb","type":"u","eng":"to complain","levels":["L21"],"kanji":"<ruby>言<rt>い</rt></ruby><ruby>う(文<rt>もん</rt></ruby><ruby>句<rt>く</rt></ruby>を)"},
    {"writing":"おく","reading":"置く","category":"verb","type":"u","eng":"to put; to lay; to place","levels":["L21"],"kanji":"<ruby>置<rt>お</rt></ruby>く"},
    {"writing":"きがつく","reading":"気が付く","category":"verb","type":"u","eng":"to notice","levels":["L21"],"kanji":"<ruby>気<rt>き</rt></ruby>が<ruby>付<rt>つ</rt></ruby>く"},
    {"writing":"ける","reading":"ける","category":"verb","type":"u","eng":"to kick","levels":["L21"],"kanji":"ける"},
    {"writing":"さす","reading":"刺す","category":"verb","type":"u","eng":"to bite","levels":["L21"],"kanji":"<ruby>刺<rt>さ</rt></ruby>す"},
    {"writing":"さわる","reading":"触る","category":"verb","type":"u","eng":"to touch","levels":["L21"],"kanji":"<ruby>触<rt>さわ</rt></ruby>る"},
    {"writing":"つかまる","reading":"捕まる","category":"verb","type":"u","eng":"to be arrested; to be caught","levels":["L21"],"kanji":"<ruby>捕<rt>つか</rt></ruby>まる"},
    {"writing":"つつむ","reading":"包む","category":"verb","type":"u","eng":"to wrap; to cover","levels":["L21"],"kanji":"<ruby>包<rt>つつ</rt></ruby>む"},
    {"writing":"なぐる","reading":"殴る","category":"verb","type":"u","eng":"to strike; to hit; to punch","levels":["L21"],"kanji":"<ruby>殴<rt>なぐ</rt></ruby>る"},
    {"writing":"ぬすむ","reading":"盗む","category":"verb","type":"u","eng":"to steal; to rob","levels":["L21"],"kanji":"<ruby>盗<rt>ぬす</rt></ruby>む"},
    {"writing":"はる","reading":"貼る","category":"verb","type":"u","eng":"to post; to stick","levels":["L21"],"kanji":"<ruby>貼<rt>は</rt></ruby>る"},
    {"writing":"ふむ","reading":"踏む","category":"verb","type":"u","eng":"to step on","levels":["L21"],"kanji":"<ruby>踏<rt>ふ</rt></ruby>む"},
    {"writing":"ふる","reading":"ふる","category":"verb","type":"u","eng":"to turn down (somebody); to reject; to jilt","levels":["L21"],"kanji":"ふる"},
    {"writing":"もんくをいう","reading":"文句を言う","category":"verb","type":"u","eng":"to complain","levels":["L21"],"kanji":"<ruby>文<rt>もん</rt></ruby><ruby>句<rt>く</rt></ruby>を<ruby>言<rt>い</rt></ruby>う"},
    {"writing":"やく","reading":"焼く","category":"verb","type":"u","eng":"to bake; to burn; to grill","levels":["L21"],"kanji":"<ruby>焼<rt>や</rt></ruby>く"},
    {"writing":"やる","reading":"やる","category":"verb","type":"u","eng":"to give (to pets, plants, younger siblings, etc.)","levels":["L21"],"kanji":"やる"},
    {"writing":"いじめる","reading":"いじめる","category":"verb","type":"ru","eng":"to bully ","levels":["L21"],"kanji":"いじめる"},
    {"writing":"きがえる","reading":"着替える","category":"verb","type":"ru","eng":"to change clothes ","levels":["L21"],"kanji":"<ruby>着<rt>き</rt></ruby><ruby>替<rt>が</rt></ruby>える"},
    {"writing":"くらべる","reading":"比べる","category":"verb","type":"ru","eng":"to compare ","levels":["L21"],"kanji":"<ruby>比<rt>くら</rt></ruby>べる"},
    {"writing":"しんじる","reading":"信じる","category":"verb","type":"ru","eng":"to believe ","levels":["L21"],"kanji":"<ruby>信<rt>しん</rt></ruby>じる"},
    {"writing":"ためる","reading":"ためる","category":"verb","type":"ru","eng":"to save money ","levels":["L21"],"kanji":"ためる"},
    {"writing":"ほめる","reading":"ほめる","category":"verb","type":"ru","eng":"to praise; to say nice things ","levels":["L21"],"kanji":"ほめる"},
    {"writing":"まちがえる","reading":"間違える","category":"verb","type":"ru","eng":"to make a mistake ","levels":["L21"],"kanji":"<ruby>間<rt>ま</rt></ruby><ruby>違<rt>ちが</rt></ruby>える"},
    {"writing":"みつける","reading":"見つける","category":"verb","type":"ru","eng":"to find ","levels":["L21"],"kanji":"<ruby>見<rt>み</rt></ruby>つける"},
    {"writing":"ばかにする","reading":"ばかにする","category":"verb","type":"irv","eng":"to insult; to make a fool of...","levels":["L21"],"kanji":"ばかにする"},
    {"writing":"ひるねをする","reading":"昼寝をする","category":"verb","type":"irv","eng":"to take a nap ","levels":["L21"],"kanji":"<ruby>昼<rt>ひる</rt></ruby><ruby>寝<rt>ね</rt></ruby>をする"},
    {"writing":"れんらくする","reading":"連絡する","category":"verb","type":"irv","eng":"to contact ","levels":["L21"],"kanji":"<ruby>連<rt>れん</rt></ruby><ruby>絡<rt>らく</rt></ruby>する"},
    {"writing":"おこる","reading":"起こる","category":"verb","type":"u","eng":"to occur; to happen","levels":["L21"],"kanji":"<ruby>起<rt>お</rt></ruby>こる"},
    {"writing":"かよう","reading":"通う","category":"verb","type":"u","eng":"to commute to","levels":["L21"],"kanji":"<ruby>通<rt>かよ</rt></ruby>う"},
    {"writing":"きにする","reading":"気にする","category":"verb","type":"irv","eng":"to worry ","levels":["L21"],"kanji":"<ruby>気<rt>き</rt></ruby>にする"},
    {"writing":"ぜいたくをする","reading":"ぜいたくをする","category":"verb","type":"irv","eng":"to indulge in luxury ","levels":["L21"],"kanji":"ぜいたくをする"},
    {"writing":"にゅういんする","reading":"入院する","category":"verb","type":"irv","eng":"to be hospitalized ","levels":["L21"],"kanji":"<ruby>入<rt>にゅう</rt></ruby><ruby>院<rt>いん</rt></ruby>する"},
    {"writing":"かぜがふく","reading":"風が吹く","category":"verb","type":"u","eng":"the wind blows","levels":["L22"],"kanji":"<ruby>風<rt>かぜ</rt></ruby>が<ruby>吹<rt>ふ</rt></ruby>く"},
    {"writing":"かつ","reading":"勝つ","category":"verb","type":"u","eng":"to win","levels":["L22"],"kanji":"<ruby>勝<rt>か</rt></ruby>つ"},
    {"writing":"コピーをとる","reading":"コピーを取る","category":"verb","type":"u","eng":"to make a photocopy","levels":["L22"],"kanji":"コピーを<ruby>取<rt>と</rt></ruby>る"},
    {"writing":"はこぶ","reading":"運ぶ","category":"verb","type":"u","eng":"to carry","levels":["L22"],"kanji":"<ruby>運<rt>はこ</rt></ruby>ぶ"},
    {"writing":"ひろう","reading":"拾う","category":"verb","type":"u","eng":"to pick up (something)","levels":["L22"],"kanji":"<ruby>拾<rt>ひろ</rt></ruby>う"},
    {"writing":"まにあう","reading":"間に合う","category":"verb","type":"u","eng":"to be in time","levels":["L22"],"kanji":"<ruby>間<rt>ま</rt></ruby>に<ruby>合<rt>あ</rt></ruby>う"},
    {"writing":"けいかくをたてる","reading":"計画を立てる","category":"verb","type":"ru","eng":"to make a plan ","levels":["L22"],"kanji":"<ruby>計<rt>けい</rt></ruby><ruby>画<rt>かく</rt></ruby>を<ruby>立<rt>た</rt></ruby>てる"},
    {"writing":"そだてる","reading":"育てる","category":"verb","type":"ru","eng":"to raise; to bring up ","levels":["L22"],"kanji":"<ruby>育<rt>そだ</rt></ruby>てる"},
    {"writing":"まける","reading":"負ける","category":"verb","type":"ru","eng":"to lose (a match) ","levels":["L22"],"kanji":"<ruby>負<rt>ま</rt></ruby>ける"},
    {"writing":"おねがいする","reading":"お願いする","category":"verb","type":"irv","eng":"to request help ","levels":["L22"],"kanji":"お<ruby>願<rt>ねが</rt></ruby>いする"},
    {"writing":"さんせいする","reading":"賛成する","category":"verb","type":"irv","eng":"to agree ","levels":["L22"],"kanji":"<ruby>賛<rt>さん</rt></ruby><ruby>成<rt>せい</rt></ruby>する"},
    {"writing":"しっぱいする","reading":"失敗する","category":"verb","type":"irv","eng":"to fail; to be unsuccessful ","levels":["L22"],"kanji":"<ruby>失<rt>しっ</rt></ruby><ruby>敗<rt>ぱい</rt></ruby>する"},
    {"writing":"てつやする","reading":"徹夜する","category":"verb","type":"irv","eng":"to stay up all night ","levels":["L22"],"kanji":"<ruby>徹<rt>てつ</rt></ruby><ruby>夜<rt>や</rt></ruby>する"},
    {"writing":"はんたいする","reading":"反対する","category":"verb","type":"irv","eng":"to oppose; to object to ","levels":["L22"],"kanji":"<ruby>反<rt>はん</rt></ruby><ruby>対<rt>たい</rt></ruby>する"},
    {"writing":"ほんやくする","reading":"翻訳する","category":"verb","type":"irv","eng":"to translate ","levels":["L22"],"kanji":"<ruby>翻<rt>ほん</rt></ruby><ruby>訳<rt>やく</rt></ruby>する"},
    {"writing":"うまくいく","reading":"うまくいく","category":"verb","type":"u","eng":"to go well","levels":["L22"],"kanji":"うまくいく"},
    {"writing":"うらやましがる","reading":"うらやましがる","category":"verb","type":"u","eng":"(somebody is) envious","levels":["L22"],"kanji":"うらやましがる"},
    {"writing":"にげる","reading":"逃げる","category":"verb","type":"ru","eng":"to run away; to escape ","levels":["L22"],"kanji":"<ruby>逃<rt>に</rt></ruby>げる"},
    {"writing":"あめがやむ","reading":"雨がやむ","category":"verb","type":"u","eng":"the rain stops","levels":["L23"],"kanji":"<ruby>雨<rt>あめ</rt></ruby>がやむ"},
    {"writing":"いう（わるぐちを）","suffix":"いう（わるぐちを）","reading":"言う（悪口を）","category":"verb","type":"u","eng":"to talk behind someone’s back","levels":["L23"],"kanji":"<ruby>言<rt>い</rt></ruby><ruby>う(悪<rt>わる</rt></ruby><ruby>口<rt>ぐち</rt></ruby>を)"},
    {"writing":"いなくなる","reading":"いなくなる","category":"verb","type":"u","eng":"(someone) is gone; to disappear","levels":["L23"],"kanji":"いなくなる"},
    {"writing":"おなかをこわす","reading":"おなかをこわす","category":"verb","type":"u","eng":"to have a stomachache","levels":["L23"],"kanji":"おなかをこわす"},
    {"writing":"きにいる","reading":"気に入る","category":"verb","type":"u","eng":"to find something agreeable","levels":["L23"],"kanji":"<ruby>気<rt>き</rt></ruby>に<ruby>入<rt>い</rt></ruby>る"},
    {"writing":"なくなる","reading":"なくなる","category":"verb","type":"u","eng":"to be lost; to disappear","levels":["L23"],"kanji":"なくなる"},
    {"writing":"わるぐちをいう","reading":"悪口を言う","category":"verb","type":"u","eng":"to talk behind someone’s back","levels":["L23"],"kanji":"<ruby>悪<rt>わる</rt></ruby><ruby>口<rt>ぐち</rt></ruby>を<ruby>言<rt>い</rt></ruby>う"},
    {"writing":"はなれる","reading":"離れる","category":"verb","type":"ru","eng":"(something/someone) separates; parts from ","levels":["L23"],"kanji":"<ruby>離<rt>はな</rt></ruby>れる"},
    {"writing":"かおをする","prefix":"～","reading":"顔をする","category":"verb","type":"irv","eng":"to look...(facial expression) ","levels":["L23"],"kanji":"<ruby>顔<rt>かお</rt></ruby>をする"},
    {"writing":"がまんする","reading":"我慢する","category":"verb","type":"irv","eng":"to be tolerant/patient ","levels":["L23"],"kanji":"<ruby>我<rt>が</rt></ruby><ruby>慢<rt>まん</rt></ruby>する"},
    {"writing":"カンニングする","reading":"カンニングする","category":"verb","type":"irv","eng":"to cheat in an exam ","levels":["L23"],"kanji":"カンニングする"},
    {"writing":"せわをする","reading":"世話をする","category":"verb","type":"irv","eng":"to take care of...","levels":["L23"],"kanji":"<ruby>世<rt>せ</rt></ruby><ruby>話<rt>わ</rt></ruby>をする"},
    {"writing":"チェックする","reading":"チェックする","category":"verb","type":"irv","eng":"to check ","levels":["L23"],"kanji":"チェックする"},
    {"writing":"どうじょうする","reading":"同情する","category":"verb","type":"irv","eng":"to sympathize ","levels":["L23"],"kanji":"<ruby>同<rt>どう</rt></ruby><ruby>情<rt>じょう</rt></ruby>する"},
    {"writing":"もどってくる","reading":"戻ってくる","category":"verb","type":"irv","eng":"(something/someone) comes back ","levels":["L23"],"kanji":"<ruby>戻<rt>もど</rt></ruby>ってくる"},
    {"writing":"ゆうしょうする","reading":"優勝する","category":"verb","type":"irv","eng":"to win a championship ","levels":["L23"],"kanji":"<ruby>優<rt>ゆう</rt></ruby><ruby>勝<rt>しょう</rt></ruby>する"},
    {"writing":"あらわす","reading":"表す","category":"verb","type":"u","eng":"to express; to show","levels":["L23"],"kanji":"<ruby>表<rt>あらわ</rt></ruby>す"},
    {"writing":"キスをする","reading":"キスをする","category":"verb","type":"irv","eng":"to kiss ","levels":["L23"],"kanji":"キスをする"},
    {"writing":"いく","reading":"行く","category":"verb","type":"u","eng":"to go","levels":["L3"],"kanji":"<ruby>行<rt>い</rt></ruby>く"},
    {"writing":"かえる","reading":"帰る","category":"verb","type":"u","eng":"to go back; to return","levels":["L3"],"kanji":"<ruby>帰<rt>かえ</rt></ruby>る"},
    {"writing":"きく","reading":"聞く","category":"verb","type":"u","eng":"to listen; to hear","levels":["L3"],"kanji":"<ruby>聞<rt>き</rt></ruby>く"},
    {"writing":"のむ","reading":"飲む","category":"verb","type":"u","eng":"to drink","levels":["L3"],"kanji":"<ruby>飲<rt>の</rt></ruby>む"},
    {"writing":"はなす","reading":"話す","category":"verb","type":"u","eng":"to speak; to talk","levels":["L3"],"kanji":"<ruby>話<rt>はな</rt></ruby>す"},
    {"writing":"よむ","reading":"読む","category":"verb","type":"u","eng":"to read","levels":["L3"],"kanji":"<ruby>読<rt>よ</rt></ruby>む"},
    {"writing":"おきる","reading":"起きる","category":"verb","type":"ru","eng":"to get up ","levels":["L3"],"kanji":"<ruby>起<rt>お</rt></ruby>きる"},
    {"writing":"たべる","reading":"食べる","category":"verb","type":"ru","eng":"to eat ","levels":["L3"],"kanji":"<ruby>食<rt>た</rt></ruby>べる"},
    {"writing":"ねる","reading":"寝る","category":"verb","type":"ru","eng":"to sleep; to go to sleep ","levels":["L3"],"kanji":"<ruby>寝<rt>ね</rt></ruby>る"},
    {"writing":"みる","reading":"見る","category":"verb","type":"ru","eng":"to see; to look at; to watch ","levels":["L3"],"kanji":"<ruby>見<rt>み</rt></ruby>る"},
    {"writing":"くる","reading":"来る","category":"verb","type":"irv","eng":"to come ","levels":["L3"],"kanji":"<ruby>来<rt>く</rt></ruby>る"},
    {"writing":"する","reading":"する","category":"verb","type":"irv","eng":"to do ","levels":["L3"],"kanji":"する"},
    {"writing":"べんきょうする","reading":"勉強する","category":"verb","type":"irv","eng":"to study ","levels":["L3"],"kanji":"<ruby>勉<rt>べん</rt></ruby><ruby>強<rt>きょう</rt></ruby>する"},
    {"writing":"あう","reading":"会う","category":"verb","type":"u","eng":"to meet; to see (a person)","levels":["L4"],"kanji":"<ruby>会<rt>あ</rt></ruby>う"},
    {"writing":"ある","reading":"ある","category":"verb","type":"u","eng":"there is . . .","levels":["L4"],"kanji":"ある"},
    {"writing":"かう","reading":"買う","category":"verb","type":"u","eng":"to buy","levels":["L4"],"kanji":"<ruby>買<rt>か</rt></ruby>う"},
    {"writing":"かく","reading":"書く","category":"verb","type":"u","eng":"to write","levels":["L4"],"kanji":"<ruby>書<rt>か</rt></ruby>く"},
    {"writing":"とる","reading":"撮る","category":"verb","type":"u","eng":"to take (a picture)","levels":["L4"],"kanji":"<ruby>撮<rt>と</rt></ruby>る"},
    {"writing":"まつ","reading":"待つ","category":"verb","type":"u","eng":"to wait","levels":["L4"],"kanji":"<ruby>待<rt>ま</rt></ruby>つ"},
    {"writing":"わかる","reading":"わかる","category":"verb","type":"u","eng":"to understand","levels":["L4"],"kanji":"わかる"},
    {"writing":"いる","reading":"いる","category":"verb","type":"ru","eng":"(a person) is in...; stays at...","levels":["L4"],"kanji":"いる"},
    {"writing":"およぐ","reading":"泳ぐ","category":"verb","type":"u","eng":"to swim","levels":["L5"],"kanji":"<ruby>泳<rt>およ</rt></ruby>ぐ"},
    {"writing":"きく","reading":"聞く","category":"verb","type":"u","eng":"to ask","levels":["L5"],"kanji":"<ruby>聞<rt>き</rt></ruby>く"},
    {"writing":"のる","reading":"乗る","category":"verb","type":"u","eng":"to ride; to board","levels":["L5"],"kanji":"<ruby>乗<rt>の</rt></ruby>る"},
    {"writing":"やる","reading":"やる","category":"verb","type":"u","eng":"to do; to perform","levels":["L5"],"kanji":"やる"},
    {"writing":"でかける","reading":"出かける","category":"verb","type":"ru","eng":"to go out ","levels":["L5"],"kanji":"<ruby>出<rt>で</rt></ruby>かける"},
    {"writing":"あそぶ","reading":"遊ぶ","category":"verb","type":"u","eng":"to play; to spend time pleasantly","levels":["L6"],"kanji":"<ruby>遊<rt>あそ</rt></ruby>ぶ"},
    {"writing":"いそぐ","reading":"急ぐ","category":"verb","type":"u","eng":"to hurry","levels":["L6"],"kanji":"<ruby>急<rt>いそ</rt></ruby>ぐ"},
    {"writing":"かえす","reading":"返す","category":"verb","type":"u","eng":"to return (a thing)","levels":["L6"],"kanji":"<ruby>返<rt>かえ</rt></ruby>す"},
    {"writing":"けす","reading":"消す","category":"verb","type":"u","eng":"to turn off; to erase","levels":["L6"],"kanji":"<ruby>消<rt>け</rt></ruby>す"},
    {"writing":"しぬ","reading":"死ぬ","category":"verb","type":"u","eng":"to die","levels":["L6"],"kanji":"<ruby>死<rt>し</rt></ruby>ぬ"},
    {"writing":"すわる","reading":"座る","category":"verb","type":"u","eng":"to sit down","levels":["L6"],"kanji":"<ruby>座<rt>すわ</rt></ruby>る"},
    {"writing":"たつ","reading":"立つ","category":"verb","type":"u","eng":"to stand up","levels":["L6"],"kanji":"<ruby>立<rt>た</rt></ruby>つ"},
    {"writing":"たばこをすう","reading":"たばこを吸う","category":"verb","type":"u","eng":"to smoke","levels":["L6"],"kanji":"たばこを<ruby>吸<rt>す</rt></ruby>う"},
    {"writing":"つかう","reading":"使う","category":"verb","type":"u","eng":"to use","levels":["L6"],"kanji":"<ruby>使<rt>つか</rt></ruby>う"},
    {"writing":"てつだう","reading":"手伝う","category":"verb","type":"u","eng":"to help","levels":["L6"],"kanji":"<ruby>手<rt>て</rt></ruby><ruby>伝<rt>つだ</rt></ruby>う"},
    {"writing":"はいる","reading":"入る","category":"verb","type":"u","eng":"to enter","levels":["L6"],"kanji":"<ruby>入<rt>はい</rt></ruby>る"},
    {"writing":"もつ","reading":"持つ","category":"verb","type":"u","eng":"to carry; to hold","levels":["L6"],"kanji":"<ruby>持<rt>も</rt></ruby>つ"},
    {"writing":"やすむ","reading":"休む","category":"verb","type":"u","eng":"to be absent (from); to rest","levels":["L6"],"kanji":"<ruby>休<rt>やす</rt></ruby>む"},
    {"writing":"あける","reading":"開ける","category":"verb","type":"ru","eng":"to open (something) ","levels":["L6"],"kanji":"<ruby>開<rt>あ</rt></ruby>ける"},
    {"writing":"おしえる","reading":"教える","category":"verb","type":"ru","eng":"to teach; to instruct ","levels":["L6"],"kanji":"<ruby>教<rt>おし</rt></ruby>える"},
    {"writing":"おりる","reading":"降りる","category":"verb","type":"ru","eng":"to get off ","levels":["L6"],"kanji":"<ruby>降<rt>お</rt></ruby>りる"},
    {"writing":"かりる","reading":"借りる","category":"verb","type":"ru","eng":"to borrow ","levels":["L6"],"kanji":"<ruby>借<rt>か</rt></ruby>りる"},
    {"writing":"しめる","reading":"閉める","category":"verb","type":"ru","eng":"to close (something) ","levels":["L6"],"kanji":"<ruby>閉<rt>し</rt></ruby>める"},
    {"writing":"シャワーをあびる","reading":"シャワーを浴びる","category":"verb","type":"ru","eng":"to take a shower ","levels":["L6"],"kanji":"シャワーを<ruby>浴<rt>あ</rt></ruby>びる"},
    {"writing":"つける","reading":"つける","category":"verb","type":"ru","eng":"to turn on ","levels":["L6"],"kanji":"つける"},
    {"writing":"わすれる","reading":"忘れる","category":"verb","type":"ru","eng":"to forget; to leave behind ","levels":["L6"],"kanji":"<ruby>忘<rt>わす</rt></ruby>れる"},
    {"writing":"つれてくる","reading":"連れてくる","category":"verb","type":"irv","eng":"to bring (a person) ","levels":["L6"],"kanji":"<ruby>連<rt>つ</rt></ruby>れてくる"},
    {"writing":"でんわする","reading":"電話する","category":"verb","type":"irv","eng":"to call ","levels":["L6"],"kanji":"<ruby>電<rt>でん</rt></ruby><ruby>話<rt>わ</rt></ruby>する"},
    {"writing":"もってくる","reading":"持ってくる","category":"verb","type":"irv","eng":"to bring (a thing) ","levels":["L6"],"kanji":"<ruby>持<rt>も</rt></ruby>ってくる"},
    {"writing":"でる","reading":"出る","category":"verb","type":"ru","eng":"to appear; to attend; to exit ","levels":["L6","L9"],"kanji":"<ruby>出<rt>で</rt></ruby>る"},
    {"writing":"まがる","reading":"曲がる","category":"verb","type":"u","eng":"to turn (right/left)","levels":["L6","L20"],"kanji":"<ruby>曲<rt>ま</rt></ruby>がる"},
    {"writing":"わたる","reading":"渡る","category":"verb","type":"u","eng":"to cross","levels":["L6","L15"],"kanji":"<ruby>渡<rt>わた</rt></ruby>る"},
    {"writing":"うたう","reading":"歌う","category":"verb","type":"u","eng":"to sing","levels":["L7"],"kanji":"<ruby>歌<rt>うた</rt></ruby>う"},
    {"writing":"かぶる","reading":"かぶる","category":"verb","type":"u","eng":"to put on (a hat)","levels":["L7"],"kanji":"かぶる"},
    {"writing":"しる","reading":"知る","category":"verb","type":"u","eng":"to get to know","levels":["L7"],"kanji":"<ruby>知<rt>し</rt></ruby>る"},
    {"writing":"すむ","reading":"住む","category":"verb","type":"u","eng":"to live","levels":["L7"],"kanji":"<ruby>住<rt>す</rt></ruby>む"},
    {"writing":"はく","reading":"はく","category":"verb","type":"u","eng":"to put on (items below your waist)","levels":["L7"],"kanji":"はく"},
    {"writing":"はたらく","reading":"働く","category":"verb","type":"u","eng":"to work","levels":["L7"],"kanji":"<ruby>働<rt>はたら</rt></ruby>く"},
    {"writing":"ふとる","reading":"太る","category":"verb","type":"u","eng":"to gain weight; overweight","levels":["L7"],"kanji":"<ruby>太<rt>ふと</rt></ruby>る"},
    {"writing":"かける（めがねを）","suffix":"かける（めがねを）","reading":"かける（眼鏡を）","category":"verb","type":"ru","eng":"to put on (glasses) ","levels":["L7"],"kanji":"<ruby>かける(眼<rt>め</rt></ruby><ruby>鏡<rt>がね</rt></ruby>を)"},
    {"writing":"きる","reading":"着る","category":"verb","type":"ru","eng":"to put on (clothes above your waist) ","levels":["L7"],"kanji":"<ruby>着<rt>き</rt></ruby>る"},
    {"writing":"やせる","reading":"やせる","category":"verb","type":"ru","eng":"to lose weight ","levels":["L7"],"kanji":"やせる"},
    {"writing":"けっこんする","reading":"結婚する","category":"verb","type":"irv","eng":"to get married ","levels":["L7"],"kanji":"<ruby>結<rt>けっ</rt></ruby><ruby>婚<rt>こん</rt></ruby>する"},
    {"writing":"からだにきをつける","reading":"体に気をつける","category":"verb","type":"ru","eng":"to take care of oneself ","levels":["L7"],"kanji":"<ruby>体<rt>からだ</rt></ruby>に<ruby>気<rt>き</rt></ruby>をつける"},
    {"writing":"たのしみにする","suffix":"たのしみにする","reading":"楽しみにする","category":"verb","type":"irv","eng":"to look forward (to) ","levels":["L7"],"kanji":"<ruby>楽<rt>たの</rt></ruby>しみにする"},
    {"writing":"とる","reading":"取る","category":"verb","type":"u","eng":"to take (a class); to get (a grade)","levels":["L7","L11"],"kanji":"<ruby>取<rt>と</rt></ruby>る"},
    {"writing":"あらう","reading":"洗う","category":"verb","type":"u","eng":"to wash","levels":["L8"],"kanji":"<ruby>洗<rt>あら</rt></ruby>う"},
    {"writing":"いう","reading":"言う","category":"verb","type":"u","eng":"to say","levels":["L8"],"kanji":"<ruby>言<rt>い</rt></ruby>う"},
    {"writing":"いる","reading":"いる","category":"verb","type":"u","eng":"to need","levels":["L8"],"kanji":"いる"},
    {"writing":"おそくなる","reading":"遅くなる","category":"verb","type":"u","eng":"to be late","levels":["L8"],"kanji":"<ruby>遅<rt>おそ</rt></ruby>くなる"},
    {"writing":"おふろにはいる","reading":"お風呂に入る","category":"verb","type":"u","eng":"to take a bath","levels":["L8"],"kanji":"お<ruby>風<rt>ふ</rt></ruby><ruby>呂<rt>ろ</rt></ruby>に<ruby>入<rt>はい</rt></ruby>る"},
    {"writing":"おもう","reading":"思う","category":"verb","type":"u","eng":"to think","levels":["L8"],"kanji":"<ruby>思<rt>おも</rt></ruby>う"},
    {"writing":"つくる","reading":"作る","category":"verb","type":"u","eng":"to make","levels":["L8"],"kanji":"<ruby>作<rt>つく</rt></ruby>る"},
    {"writing":"ふろにはいる","reading":"風呂に入る","category":"verb","type":"u","eng":"to take a bath","levels":["L8"],"kanji":"<ruby>風<rt>ふ</rt></ruby><ruby>呂<rt>ろ</rt></ruby>に<ruby>入<rt>はい</rt></ruby>る"},
    {"writing":"もっていく","reading":"持っていく","category":"verb","type":"u","eng":"to take (a thing)","levels":["L8"],"kanji":"<ruby>持<rt>も</rt></ruby>っていく"},
    {"writing":"すてる","reading":"捨てる","category":"verb","type":"ru","eng":"to throw away ","levels":["L8"],"kanji":"<ruby>捨<rt>す</rt></ruby>てる"},
    {"writing":"はじめる","reading":"始める","category":"verb","type":"ru","eng":"to begin ","levels":["L8"],"kanji":"<ruby>始<rt>はじ</rt></ruby>める"},
    {"writing":"うんてんする","reading":"運転する","category":"verb","type":"irv","eng":"to drive ","levels":["L8"],"kanji":"<ruby>運<rt>うん</rt></ruby><ruby>転<rt>てん</rt></ruby>する"},
    {"writing":"せんたくする","reading":"洗濯する","category":"verb","type":"irv","eng":"to do laundry ","levels":["L8"],"kanji":"<ruby>洗<rt>せん</rt></ruby><ruby>濯<rt>たく</rt></ruby>する"},
    {"writing":"そうじする","reading":"掃除する","category":"verb","type":"irv","eng":"to clean ","levels":["L8"],"kanji":"<ruby>掃<rt>そう</rt></ruby><ruby>除<rt>じ</rt></ruby>する"},
    {"writing":"りょうりする","reading":"料理する","category":"verb","type":"irv","eng":"to cook ","levels":["L8"],"kanji":"<ruby>料<rt>りょう</rt></ruby><ruby>理<rt>り</rt></ruby>する"},
    {"writing":"こたえる","reading":"答える","category":"verb","type":"ru","eng":"to answer ","levels":["L8","L23"],"kanji":"<ruby>答<rt>こた</rt></ruby>える"},
    {"writing":"きる","reading":"切る","category":"verb","type":"u","eng":"to cut","levels":["L8","L17"],"kanji":"<ruby>切<rt>き</rt></ruby>る"},
    {"writing":"おどる","reading":"踊る","category":"verb","type":"u","eng":"to dance","levels":["L9"],"kanji":"<ruby>踊<rt>おど</rt></ruby>る"},
    {"writing":"おわる","reading":"終わる","category":"verb","type":"u","eng":"(something) ends","levels":["L9"],"kanji":"<ruby>終<rt>お</rt></ruby>わる"},
    {"writing":"くすりをのむ","reading":"薬を飲む","category":"verb","type":"u","eng":"to take medicine","levels":["L9"],"kanji":"<ruby>薬<rt>くすり</rt></ruby>を<ruby>飲<rt>の</rt></ruby>む"},
    {"writing":"にんきがある","reading":"人気がある","category":"verb","type":"u","eng":"to be popular","levels":["L9"],"kanji":"<ruby>人<rt>にん</rt></ruby><ruby>気<rt>き</rt></ruby>がある"},
    {"writing":"はじまる","reading":"始まる","category":"verb","type":"u","eng":"(something) begins","levels":["L9"],"kanji":"<ruby>始<rt>はじ</rt></ruby>まる"},
    {"writing":"ひく","reading":"弾く","category":"verb","type":"u","eng":"to play (a string instrument or piano)","levels":["L9"],"kanji":"<ruby>弾<rt>ひ</rt></ruby>く"},
    {"writing":"もらう","reading":"もらう","category":"verb","type":"u","eng":"to get (from somebody)","levels":["L9"],"kanji":"もらう"},
    {"writing":"おぼえる","reading":"覚える","category":"verb","type":"ru","eng":"to memorize ","levels":["L9"],"kanji":"<ruby>覚<rt>おぼ</rt></ruby>える"},
    {"writing":"うんどうする","reading":"運動する","category":"verb","type":"irv","eng":"to exercise ","levels":["L9"],"kanji":"<ruby>運<rt>うん</rt></ruby><ruby>動<rt>どう</rt></ruby>する"},
    {"writing":"さんぽする","reading":"散歩する","category":"verb","type":"irv","eng":"to take a walk ","levels":["L9"],"kanji":"<ruby>散<rt>さん</rt></ruby><ruby>歩<rt>ぽ</rt></ruby>する"},
    {"writing":"あんないする","reading":"案内する","category":"verb","type":"irv","eng":"to show (someone) around","levels":["L9","L16"],"kanji":"<ruby>案<rt>あん</rt></ruby><ruby>内<rt>ない</rt></ruby>する"},
    {"writing":"はなしをする","reading":"話をする","category":"verb","type":"irv","eng":"to have a talk ","levels":["L9","L19"],"kanji":"<ruby>話<rt>はなし</rt></ruby>をする"},
  ],
  "adjectives": [
        {"writing":"かんたん","suffix":"（な）","reading":"簡単","category":"adjective","type":"na","eng":"easy; simple","levels":["L10"],"kanji":"<ruby>簡<rt>かん</rt></ruby><ruby>単<rt>たん</rt></ruby>"},
    {"writing":"あたたかい","reading":"暖かい","category":"adjective","type":"i","eng":"warm","levels":["L10"],"kanji":"<ruby>暖<rt>あたた</rt></ruby>かい"},
    {"writing":"おそい","reading":"遅い","category":"adjective","type":"i","eng":"slow; late","levels":["L10"],"kanji":"<ruby>遅<rt>おそ</rt></ruby>い"},
    {"writing":"すずしい","reading":"涼しい","category":"adjective","type":"i","eng":"cool (weather)","levels":["L10"],"kanji":"<ruby>涼<rt>すず</rt></ruby>しい"},
    {"writing":"つめたい","reading":"冷たい","category":"adjective","type":"i","eng":"cold (things/people)","levels":["L10"],"kanji":"<ruby>冷<rt>つめ</rt></ruby>たい"},
    {"writing":"ねむい","reading":"眠い","category":"adjective","type":"i","eng":"sleepy","levels":["L10"],"kanji":"<ruby>眠<rt>ねむ</rt></ruby>い"},
    {"writing":"しあわせ","suffix":"（な）","reading":"幸せ","category":"adjective","type":"na","eng":"happy (lasting happiness)","levels":["L10","L13"],"kanji":"<ruby>幸<rt>しあわ</rt></ruby>せ"},
    {"writing":"かなしい","reading":"悲しい","category":"adjective","type":"i","eng":"sad","levels":["L10","L13"],"kanji":"<ruby>悲<rt>かな</rt></ruby>しい"},
    {"writing":"あかるい","reading":"明るい","category":"adjective","type":"i","eng":"cheerful","levels":["L11"],"kanji":"<ruby>明<rt>あか</rt></ruby>るい"},
    {"writing":"すてき","suffix":"（な）","reading":"素敵","category":"adjective","type":"na","eng":"nice","levels":["L12"],"kanji":"<ruby>素<rt>す</rt></ruby><ruby>敵<rt>てき</rt></ruby>"},
    {"writing":"あまい","reading":"甘い","category":"adjective","type":"i","eng":"sweet","levels":["L12"],"kanji":"<ruby>甘<rt>あま</rt></ruby>い"},
    {"writing":"いたい","reading":"痛い","category":"adjective","type":"i","eng":"hurt; painful","levels":["L12"],"kanji":"<ruby>痛<rt>いた</rt></ruby>い"},
    {"writing":"おおい","reading":"多い","category":"adjective","type":"i","eng":"there are many . . .","levels":["L12"],"kanji":"<ruby>多<rt>おお</rt></ruby>い"},
    {"writing":"せまい","reading":"狭い","category":"adjective","type":"i","eng":"narrow; not spacious","levels":["L12"],"kanji":"<ruby>狭<rt>せま</rt></ruby>い"},
    {"writing":"ひろい","reading":"広い","category":"adjective","type":"i","eng":"wide; spacious","levels":["L12"],"kanji":"<ruby>広<rt>ひろ</rt></ruby>い"},
    {"writing":"わるい","reading":"悪い","category":"adjective","type":"i","eng":"bad","levels":["L12"],"kanji":"<ruby>悪<rt>わる</rt></ruby>い"},
    {"writing":"まじめ","suffix":"（な）","reading":"まじめ","category":"adjective","type":"na","eng":"serious; sober; diligent","levels":["L12","L19"],"kanji":"まじめ"},
    {"writing":"かわいそう","suffix":"（な）","reading":"かわいそう","category":"adjective","type":"na","eng":"pitiful; feel sorry for; poor thing","levels":["L12","L23"],"kanji":"かわいそう"},
    {"writing":"きぶんがわるい","reading":"気分が悪い","category":"adjective","type":"i","eng":"not to feel well; to feel sick","levels":["L12","L13"],"kanji":"<ruby>気<rt>き</rt></ruby><ruby>分<rt>ぶん</rt></ruby>が<ruby>悪<rt>わる</rt></ruby>い"},
    {"writing":"だめ","suffix":"（な）","reading":"だめ","category":"adjective","type":"na","eng":"no good","levels":["L13"],"kanji":"だめ"},
    {"writing":"うれしい","reading":"うれしい","category":"adjective","type":"i","eng":"glad","levels":["L13"],"kanji":"うれしい"},
    {"writing":"からい","reading":"辛い","category":"adjective","type":"i","eng":"hot and spicy; salty","levels":["L13"],"kanji":"<ruby>辛<rt>から</rt></ruby>い"},
    {"writing":"きびしい","reading":"厳しい","category":"adjective","type":"i","eng":"strict","levels":["L13"],"kanji":"<ruby>厳<rt>きび</rt></ruby>しい"},
    {"writing":"すごい","reading":"すごい","category":"adjective","type":"i","eng":"incredible; awesome","levels":["L13"],"kanji":"すごい"},
    {"writing":"ちかい","reading":"近い","category":"adjective","type":"i","eng":"close; near","levels":["L13"],"kanji":"<ruby>近<rt>ちか</rt></ruby>い"},
    {"writing":"めずらしい","reading":"めずらしい","category":"adjective","type":"i","eng":"rare","levels":["L13"],"kanji":"めずらしい"},
    {"writing":"ふあん","suffix":"（な）","reading":"不安","category":"adjective","type":"na","eng":"anxious; worried","levels":["L13","L18"],"kanji":"<ruby>不<rt>ふ</rt></ruby><ruby>安<rt>あん</rt></ruby>"},
    {"writing":"おしゃれ","suffix":"（な）","reading":"おしゃれ","category":"adjective","type":"na","eng":"fashionable; stylish","levels":["L14"],"kanji":"おしゃれ"},
    {"writing":"けち","suffix":"（な）","reading":"けち","category":"adjective","type":"na","eng":"stingy; cheap","levels":["L14"],"kanji":"けち"},
    {"writing":"ほしい","reading":"欲しい","category":"adjective","type":"i","eng":"to want","levels":["L14"],"kanji":"<ruby>欲<rt>ほ</rt></ruby>しい"},
    {"writing":"きたない","reading":"汚い","category":"adjective","type":"i","eng":"dirty","levels":["L16"],"kanji":"<ruby>汚<rt>きたな</rt></ruby>い"},
    {"writing":"よわい","reading":"弱い","category":"adjective","type":"i","eng":"weak","levels":["L16"],"kanji":"<ruby>弱<rt>よわ</rt></ruby>い"},
    {"writing":"さいあく","suffix":"（な）","reading":"最悪","category":"adjective","type":"na","eng":"the worst","levels":["L17"],"kanji":"<ruby>最<rt>さい</rt></ruby><ruby>悪<rt>あく</rt></ruby>"},
    {"writing":"あぶない","reading":"危ない","category":"adjective","type":"i","eng":"dangerous","levels":["L17"],"kanji":"<ruby>危<rt>あぶ</rt></ruby>ない"},
    {"writing":"うらやましい","reading":"うらやましい","category":"adjective","type":"i","eng":"envious","levels":["L17"],"kanji":"うらやましい"},
    {"writing":"すくない","reading":"少ない","category":"adjective","type":"i","eng":"a little; a few","levels":["L17"],"kanji":"<ruby>少<rt>すく</rt></ruby>ない"},
    {"writing":"つごうがわるい","reading":"都合が悪い","category":"adjective","type":"i","eng":"inconvenient; to have a scheduling conflict","levels":["L17"],"kanji":"<ruby>都<rt>つ</rt></ruby><ruby>合<rt>ごう</rt></ruby>が<ruby>悪<rt>わる</rt></ruby>い"},
    {"writing":"つよい","reading":"強い","category":"adjective","type":"i","eng":"strong","levels":["L17"],"kanji":"<ruby>強<rt>つよ</rt></ruby>い"},
    {"writing":"たいせつ","suffix":"（な）","reading":"大切","category":"adjective","type":"na","eng":"precious; important","levels":["L18"],"kanji":"<ruby>大<rt>たい</rt></ruby><ruby>切<rt>せつ</rt></ruby>"},
    {"writing":"むり","suffix":"（な）","reading":"無理","category":"adjective","type":"na","eng":"impossible","levels":["L18"],"kanji":"<ruby>無<rt>む</rt></ruby><ruby>理<rt>り</rt></ruby>"},
    {"writing":"あかるい","reading":"明るい","category":"adjective","type":"i","eng":"bright","levels":["L18"],"kanji":"<ruby>明<rt>あか</rt></ruby>るい"},
    {"writing":"くらい","reading":"暗い","category":"adjective","type":"i","eng":"dark","levels":["L18"],"kanji":"<ruby>暗<rt>くら</rt></ruby>い"},
    {"writing":"はずかしい","reading":"恥ずかしい","category":"adjective","type":"i","eng":"embarrassing; to feel embarrassed","levels":["L18"],"kanji":"<ruby>恥<rt>は</rt></ruby>ずかしい"},
    {"writing":"したしい","reading":"親しい","category":"adjective","type":"i","eng":"close; intimate","levels":["L18"],"kanji":"<ruby>親<rt>した</rt></ruby>しい"},
    {"writing":"なかがいい","reading":"仲がいい","category":"adjective","type":"i","eng":"be on good/close terms; to get along well","levels":["L19"],"kanji":"<ruby>仲<rt>なか</rt></ruby>がいい"},
    {"writing":"なつかしい","reading":"なつかしい","category":"adjective","type":"i","eng":"to miss; to long for","levels":["L19"],"kanji":"なつかしい"},
    {"writing":"おいしい","reading":"おいしい","category":"adjective","type":"i","eng":"delicious","levels":["L2"],"kanji":"おいしい"},
    {"writing":"たかい","reading":"高い","category":"adjective","type":"i","eng":"expensive; high","levels":["L2"],"kanji":"<ruby>高<rt>たか</rt></ruby>い"},
    {"writing":"ふしぎ","suffix":"（な）","reading":"不思議","category":"adjective","type":"na","eng":"mysterious","levels":["L20"],"kanji":"<ruby>不<rt>ふ</rt></ruby><ruby>思<rt>し</rt></ruby><ruby>議<rt>ぎ</rt></ruby>"},
    {"writing":"おもい","reading":"重い","category":"adjective","type":"i","eng":"heavy; serious (illness)","levels":["L20"],"kanji":"<ruby>重<rt>おも</rt></ruby>い"},
    {"writing":"かるい","reading":"軽い","category":"adjective","type":"i","eng":"light","levels":["L20"],"kanji":"<ruby>軽<rt>かる</rt></ruby>い"},
    {"writing":"あんぜん","suffix":"（な）","reading":"安全","category":"adjective","type":"na","eng":"safe","levels":["L21"],"kanji":"<ruby>安<rt>あん</rt></ruby><ruby>全<rt>ぜん</rt></ruby>"},
    {"writing":"へん","suffix":"（な）","reading":"変","category":"adjective","type":"na","eng":"strange; unusual","levels":["L21"],"kanji":"<ruby>変<rt>へん</rt></ruby>"},
    {"writing":"めちゃくちゃ","suffix":"（な）","reading":"めちゃくちゃ","category":"adjective","type":"na","eng":"messy; disorganized","levels":["L21"],"kanji":"めちゃくちゃ"},
    {"writing":"とおい","reading":"遠い","category":"adjective","type":"i","eng":"far (away)","levels":["L21"],"kanji":"<ruby>遠<rt>とお</rt></ruby>い"},
    {"writing":"ひどい","reading":"ひどい","category":"adjective","type":"i","eng":"awful","levels":["L21"],"kanji":"ひどい"},
    {"writing":"ふべん","suffix":"（な）","reading":"不便","category":"adjective","type":"na","eng":"inconvenient","levels":["L21"],"kanji":"<ruby>不<rt>ふ</rt></ruby><ruby>便<rt>べん</rt></ruby>"},
    {"writing":"しんぱい","suffix":"（な）","reading":"心配","category":"adjective","type":"na","eng":"worried about","levels":["L21","L22"],"kanji":"<ruby>心<rt>しん</rt></ruby><ruby>配<rt>ぱい</rt></ruby>"},
    {"writing":"びんぼう","suffix":"（な）","reading":"貧乏","category":"adjective","type":"na","eng":"poor","levels":["L22"],"kanji":"<ruby>貧<rt>びん</rt></ruby><ruby>乏<rt>ぼう</rt></ruby>"},
    {"writing":"ぺらぺら","suffix":"（な）","reading":"ぺらぺら","category":"adjective","type":"na","eng":"fluent","levels":["L22"],"kanji":"ぺらぺら"},
    {"writing":"らく","suffix":"（な）","reading":"楽","category":"adjective","type":"na","eng":"easy; comfortable","levels":["L22"],"kanji":"<ruby>楽<rt>らく</rt></ruby>"},
    {"writing":"うるさい","reading":"うるさい","category":"adjective","type":"i","eng":"noisy; annoying","levels":["L22"],"kanji":"うるさい"},
    {"writing":"まちどおしい","reading":"待ち遠しい","category":"adjective","type":"i","eng":"to wait eagerly for . . .","levels":["L22"],"kanji":"<ruby>待<rt>ま</rt></ruby>ち<ruby>遠<rt>どお</rt></ruby>しい"},
    {"writing":"まずい","reading":"まずい","category":"adjective","type":"i","eng":"(food is) terrible","levels":["L23"],"kanji":"まずい"},
    {"writing":"いい","reading":"いい","category":"adjective","type":"i","eng":"good","levels":["L3"],"kanji":"いい"},
    {"writing":"はやい","reading":"早い","category":"adjective","type":"i","eng":"early","levels":["L3"],"kanji":"<ruby>早<rt>はや</rt></ruby>い"},
    {"writing":"きらい","suffix":"（な）","reading":"嫌い","category":"adjective","type":"na","eng":"disgusted with; to dislike","levels":["L5"],"kanji":"<ruby>嫌<rt>きら</rt></ruby>い"},
    {"writing":"きれい","suffix":"（な）","reading":"きれい","category":"adjective","type":"na","eng":"beautiful; clean","levels":["L5"],"kanji":"きれい"},
    {"writing":"げんき","suffix":"（な）","reading":"元気","category":"adjective","type":"na","eng":"healthy; energetic","levels":["L5"],"kanji":"<ruby>元<rt>げん</rt></ruby><ruby>気<rt>き</rt></ruby>"},
    {"writing":"しずか","suffix":"（な）","reading":"静か","category":"adjective","type":"na","eng":"quiet","levels":["L5"],"kanji":"<ruby>静<rt>しず</rt></ruby>か"},
    {"writing":"すき","suffix":"（な）","reading":"好き","category":"adjective","type":"na","eng":"fond of; to like","levels":["L5"],"kanji":"<ruby>好<rt>す</rt></ruby>き"},
    {"writing":"だいきらい","suffix":"（な）","reading":"大嫌い","category":"adjective","type":"na","eng":"to hate","levels":["L5"],"kanji":"<ruby>大<rt>だい</rt></ruby><ruby>嫌<rt>きら</rt></ruby>い"},
    {"writing":"だいすき","suffix":"（な）","reading":"大好き","category":"adjective","type":"na","eng":"very fond of; to love","levels":["L5"],"kanji":"<ruby>大<rt>だい</rt></ruby><ruby>好<rt>す</rt></ruby>き"},
    {"writing":"にぎやか","suffix":"（な）","reading":"にぎやか","category":"adjective","type":"na","eng":"lively","levels":["L5"],"kanji":"にぎやか"},
    {"writing":"ひま","suffix":"（な）","reading":"暇","category":"adjective","type":"na","eng":"not busy; free (time)","levels":["L5"],"kanji":"<ruby>暇<rt>ひま</rt></ruby>"},
    {"writing":"あたらしい","reading":"新しい","category":"adjective","type":"i","eng":"new","levels":["L5"],"kanji":"<ruby>新<rt>あたら</rt></ruby>しい"},
    {"writing":"あつい","reading":"熱い","category":"adjective","type":"i","eng":"hot (thing)","levels":["L5"],"kanji":"<ruby>熱<rt>あつ</rt></ruby>い"},
    {"writing":"あつい","reading":"暑い","category":"adjective","type":"i","eng":"hot (weather)","levels":["L5"],"kanji":"<ruby>暑<rt>あつ</rt></ruby>い"},
    {"writing":"いそがしい","reading":"忙しい","category":"adjective","type":"i","eng":"busy (people/days)","levels":["L5"],"kanji":"<ruby>忙<rt>いそが</rt></ruby>しい"},
    {"writing":"おおきい","reading":"大きい","category":"adjective","type":"i","eng":"large","levels":["L5"],"kanji":"<ruby>大<rt>おお</rt></ruby>きい"},
    {"writing":"おもしろい","reading":"面白い","category":"adjective","type":"i","eng":"interesting; funny","levels":["L5"],"kanji":"<ruby>面<rt>おも</rt></ruby><ruby>白<rt>しろ</rt></ruby>い"},
    {"writing":"かっこいい","reading":"かっこいい","category":"adjective","type":"i","eng":"good-looking","levels":["L5"],"kanji":"かっこいい"},
    {"writing":"こわい","reading":"怖い","category":"adjective","type":"i","eng":"frightening","levels":["L5"],"kanji":"<ruby>怖<rt>こわ</rt></ruby>い"},
    {"writing":"さむい","reading":"寒い","category":"adjective","type":"i","eng":"cold (weather)","levels":["L5"],"kanji":"<ruby>寒<rt>さむ</rt></ruby>い"},
    {"writing":"たのしい","reading":"楽しい","category":"adjective","type":"i","eng":"fun","levels":["L5"],"kanji":"<ruby>楽<rt>たの</rt></ruby>しい"},
    {"writing":"ちいさい","reading":"小さい","category":"adjective","type":"i","eng":"small","levels":["L5"],"kanji":"<ruby>小<rt>ちい</rt></ruby>さい"},
    {"writing":"つまらない","reading":"つまらない","category":"adjective","type":"i","eng":"boring","levels":["L5"],"kanji":"つまらない"},
    {"writing":"ふるい","reading":"古い","category":"adjective","type":"i","eng":"old (thing)","levels":["L5"],"kanji":"<ruby>古<rt>ふる</rt></ruby>い"},
    {"writing":"むずかしい","reading":"難しい","category":"adjective","type":"i","eng":"difficult","levels":["L5"],"kanji":"<ruby>難<rt>むずか</rt></ruby>しい"},
    {"writing":"やさしい","reading":"やさしい","category":"adjective","type":"i","eng":"easy (problem); kind (person)","levels":["L5"],"kanji":"やさしい"},
    {"writing":"やすい","reading":"安い","category":"adjective","type":"i","eng":"inexpensive; cheap (thing)","levels":["L5"],"kanji":"<ruby>安<rt>やす</rt></ruby>い"},
    {"writing":"たいへん","suffix":"（な）","reading":"大変","category":"adjective","type":"na","eng":"tough (situation)","levels":["L5","L6"],"kanji":"<ruby>大<rt>たい</rt></ruby><ruby>変<rt>へん</rt></ruby>"},
    {"writing":"しんせつ","suffix":"（な）","reading":"親切","category":"adjective","type":"na","eng":"kind","levels":["L7"],"kanji":"<ruby>親<rt>しん</rt></ruby><ruby>切<rt>せつ</rt></ruby>"},
    {"writing":"べんり","suffix":"（な）","reading":"便利","category":"adjective","type":"na","eng":"convenient","levels":["L7"],"kanji":"<ruby>便<rt>べん</rt></ruby><ruby>利<rt>り</rt></ruby>"},
    {"writing":"あたまがいい","reading":"頭がいい","category":"adjective","type":"i","eng":"bright; smart; clever","levels":["L7"],"kanji":"<ruby>頭<rt>あたま</rt></ruby>がいい"},
    {"writing":"かわいい","reading":"かわいい","category":"adjective","type":"i","eng":"cute","levels":["L7"],"kanji":"かわいい"},
    {"writing":"せがたかい","reading":"背が高い","category":"adjective","type":"i","eng":"tall (stature)","levels":["L7"],"kanji":"<ruby>背<rt>せ</rt></ruby>が<ruby>高<rt>たか</rt></ruby>い"},
    {"writing":"せがひくい","reading":"背が低い","category":"adjective","type":"i","eng":"short (stature)","levels":["L7"],"kanji":"<ruby>背<rt>せ</rt></ruby>が<ruby>低<rt>ひく</rt></ruby>い"},
    {"writing":"ながい","reading":"長い","category":"adjective","type":"i","eng":"long","levels":["L7"],"kanji":"<ruby>長<rt>なが</rt></ruby>い"},
    {"writing":"はやい","reading":"速い","category":"adjective","type":"i","eng":"fast","levels":["L7"],"kanji":"<ruby>速<rt>はや</rt></ruby>い"},
    {"writing":"みじかい","reading":"短い","category":"adjective","type":"i","eng":"short (length)","levels":["L7"],"kanji":"<ruby>短<rt>みじか</rt></ruby>い"},
    {"writing":"じょうず","suffix":"（な）","reading":"上手","category":"adjective","type":"na","eng":"skillful; good at . . .","levels":["L8"],"kanji":"<ruby>上<rt>じょう</rt></ruby><ruby>手<rt>ず</rt></ruby>"},
    {"writing":"へた","suffix":"（な）","reading":"下手","category":"adjective","type":"na","eng":"clumsy; poor at . . .","levels":["L8"],"kanji":"<ruby>下<rt>へ</rt></ruby><ruby>手<rt>た</rt></ruby>"},
    {"writing":"ゆうめい","suffix":"（な）","reading":"有名","category":"adjective","type":"na","eng":"famous","levels":["L8"],"kanji":"<ruby>有<rt>ゆう</rt></ruby><ruby>名<rt>めい</rt></ruby>"},
    {"writing":"いじわる","suffix":"（な）","reading":"意地悪","category":"adjective","type":"na","eng":"mean-spirited","levels":["L9"],"kanji":"<ruby>意<rt>い</rt></ruby><ruby>地<rt>じ</rt></ruby><ruby>悪<rt>わる</rt></ruby>"},
    {"writing":"さびしい","reading":"寂しい","category":"adjective","type":"i","eng":"lonely","levels":["L9"],"kanji":"<ruby>寂<rt>さび</rt></ruby>しい"},
    {"writing":"わかい","reading":"若い","category":"adjective","type":"i","eng":"young","levels":["L9"],"kanji":"<ruby>若<rt>わか</rt></ruby>い"},
    {"writing":"いろいろ","suffix":"（な）","reading":"いろいろ","category":"adjective","type":"na","eng":"various; different kinds of","levels":["L9","L13"],"kanji":"いろいろ"},
    {"writing":"あおい","reading":"青い","category":"adjective","type":"i","eng":"blue","levels":["L9","L9"],"kanji":"<ruby>青<rt>あお</rt></ruby>い"},
    {"writing":"あかい","reading":"赤い","category":"adjective","type":"i","eng":"red","levels":["L9","L9"],"kanji":"<ruby>赤<rt>あか</rt></ruby>い"},
    {"writing":"くろい","reading":"黒い","category":"adjective","type":"i","eng":"black","levels":["L9","L9"],"kanji":"<ruby>黒<rt>くろ</rt></ruby>い"},
    {"writing":"しろい","reading":"白い","category":"adjective","type":"i","eng":"white","levels":["L9","L9"],"kanji":"<ruby>白<rt>しろ</rt></ruby>い"},
    {"writing":"かおがあおい","reading":"顔が青い","category":"adjective","type":"i","eng":"to look pale","levels":["L9"],"kanji":"<ruby>顔<rt>かお</rt></ruby>が<ruby>青<rt>あお</rt></ruby>い"},
    {"writing":"きいろい","reading":"黄色い","category":"adjective","type":"i","eng":"yellow","levels":["L9"],"kanji":"<ruby>黄<rt>き</rt></ruby><ruby>色<rt>いろ</rt></ruby>い"},
    {"writing":"ちゃいろい","reading":"茶色い","category":"adjective","type":"i","eng":"brown","levels":["L9"],"kanji":"<ruby>茶<rt>ちゃ</rt></ruby><ruby>色<rt>いろ</rt></ruby>い"},
  ]
};